CREATE TABLE public.activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_no TEXT,
  discipline TEXT NOT NULL,
  building TEXT,
  room TEXT,
  work_scope TEXT,
  milestone TEXT,
  subcontractor TEXT,
  activity TEXT NOT NULL,
  unit TEXT,
  done_quantity NUMERIC,
  total_quantity NUMERIC,
  planned_progress NUMERIC,
  actual_progress NUMERIC,
  predecessor TEXT,
  successor TEXT,
  start_date DATE,
  finish_date DATE,
  source_file TEXT NOT NULL,
  baseline_date DATE NOT NULL DEFAULT DATE '2026-09-04',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT ON public.activities TO anon;
GRANT SELECT ON public.activities TO authenticated;
GRANT ALL ON public.activities TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.activities_id_seq TO service_role;

ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read project activities"
ON public.activities
FOR SELECT
TO anon, authenticated
USING (true);

CREATE INDEX activities_discipline_idx ON public.activities (discipline);
CREATE INDEX activities_building_idx ON public.activities (building);
CREATE INDEX activities_milestone_idx ON public.activities (milestone);
CREATE INDEX activities_finish_date_idx ON public.activities (finish_date);
CREATE INDEX activities_subcontractor_idx ON public.activities (subcontractor);