/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDelaysRouteImport } from './routes/_authenticated/delays'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedRawDataRouteImport } from './routes/_authenticated/raw-data'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedTodayReportRouteImport } from './routes/_authenticated/today-report'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedManpowerIndexRouteImport } from './routes/_authenticated/manpower.index'
import { Route as AuthenticatedManpowerCompareRouteImport } from './routes/_authenticated/manpower.compare'
import { Route as AuthenticatedManpowerMastersRouteImport } from './routes/_authenticated/manpower.masters'
import { Route as AuthenticatedManpowerMembersRouteImport } from './routes/_authenticated/manpower.members'
import { Route as AuthenticatedManpowerTrendRouteImport } from './routes/_authenticated/manpower.trend'
import { Route as AuthenticatedTcElecRouteImport } from './routes/_authenticated/tc.elec'
import { Route as AuthenticatedTcListRouteImport } from './routes/_authenticated/tc.list'
import { Route as AuthenticatedTcMechRouteImport } from './routes/_authenticated/tc.mech'
import { Route as AuthenticatedTcProgressRouteImport } from './routes/_authenticated/tc.progress'
import { Route as ApiPublicManpowerSyncRouteImport } from './routes/api/public/manpower-sync'
import { Route as ApiPublicSafetyReportRouteImport } from './routes/api/public/safety-report'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDelaysRoute = AuthenticatedDelaysRouteImport.update({
  id: '/delays',
  path: '/delays',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRawDataRoute = AuthenticatedRawDataRouteImport.update({
  id: '/raw-data',
  path: '/raw-data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayReportRoute =
  AuthenticatedTodayReportRouteImport.update({
    id: '/today-report',
    path: '/today-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManpowerIndexRoute =
  AuthenticatedManpowerIndexRouteImport.update({
    id: '/manpower/',
    path: '/manpower/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManpowerCompareRoute =
  AuthenticatedManpowerCompareRouteImport.update({
    id: '/manpower/compare',
    path: '/manpower/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManpowerMastersRoute =
  AuthenticatedManpowerMastersRouteImport.update({
    id: '/manpower/masters',
    path: '/manpower/masters',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManpowerMembersRoute =
  AuthenticatedManpowerMembersRouteImport.update({
    id: '/manpower/members',
    path: '/manpower/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManpowerTrendRoute =
  AuthenticatedManpowerTrendRouteImport.update({
    id: '/manpower/trend',
    path: '/manpower/trend',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTcElecRoute = AuthenticatedTcElecRouteImport.update({
  id: '/tc/elec',
  path: '/tc/elec',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTcListRoute = AuthenticatedTcListRouteImport.update({
  id: '/tc/list',
  path: '/tc/list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTcMechRoute = AuthenticatedTcMechRouteImport.update({
  id: '/tc/mech',
  path: '/tc/mech',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTcProgressRoute = AuthenticatedTcProgressRouteImport.update({
  id: '/tc/progress',
  path: '/tc/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicManpowerSyncRoute = ApiPublicManpowerSyncRouteImport.update({
  id: '/api/public/manpower-sync',
  path: '/api/public/manpower-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSafetyReportRoute = ApiPublicSafetyReportRouteImport.update({
  id: '/api/public/safety-report',
  path: '/api/public/safety-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delays': typeof AuthenticatedDelaysRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/raw-data': typeof AuthenticatedRawDataRoute
  '/report': typeof AuthenticatedReportRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/today': typeof AuthenticatedTodayRoute
  '/today-report': typeof AuthenticatedTodayReportRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/users': typeof AuthenticatedUsersRoute
  '/manpower/compare': typeof AuthenticatedManpowerCompareRoute
  '/manpower/masters': typeof AuthenticatedManpowerMastersRoute
  '/manpower/members': typeof AuthenticatedManpowerMembersRoute
  '/manpower/trend': typeof AuthenticatedManpowerTrendRoute
  '/tc/elec': typeof AuthenticatedTcElecRoute
  '/tc/list': typeof AuthenticatedTcListRoute
  '/tc/mech': typeof AuthenticatedTcMechRoute
  '/tc/progress': typeof AuthenticatedTcProgressRoute
  '/api/public/manpower-sync': typeof ApiPublicManpowerSyncRoute
  '/api/public/safety-report': typeof ApiPublicSafetyReportRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/manpower/': typeof AuthenticatedManpowerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delays': typeof AuthenticatedDelaysRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/raw-data': typeof AuthenticatedRawDataRoute
  '/report': typeof AuthenticatedReportRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/today': typeof AuthenticatedTodayRoute
  '/today-report': typeof AuthenticatedTodayReportRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/users': typeof AuthenticatedUsersRoute
  '/manpower/compare': typeof AuthenticatedManpowerCompareRoute
  '/manpower/masters': typeof AuthenticatedManpowerMastersRoute
  '/manpower/members': typeof AuthenticatedManpowerMembersRoute
  '/manpower/trend': typeof AuthenticatedManpowerTrendRoute
  '/tc/elec': typeof AuthenticatedTcElecRoute
  '/tc/list': typeof AuthenticatedTcListRoute
  '/tc/mech': typeof AuthenticatedTcMechRoute
  '/tc/progress': typeof AuthenticatedTcProgressRoute
  '/api/public/manpower-sync': typeof ApiPublicManpowerSyncRoute
  '/api/public/safety-report': typeof ApiPublicSafetyReportRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/manpower': typeof AuthenticatedManpowerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/delays': typeof AuthenticatedDelaysRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/raw-data': typeof AuthenticatedRawDataRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/today-report': typeof AuthenticatedTodayReportRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/manpower/compare': typeof AuthenticatedManpowerCompareRoute
  '/_authenticated/manpower/masters': typeof AuthenticatedManpowerMastersRoute
  '/_authenticated/manpower/members': typeof AuthenticatedManpowerMembersRoute
  '/_authenticated/manpower/trend': typeof AuthenticatedManpowerTrendRoute
  '/_authenticated/tc/elec': typeof AuthenticatedTcElecRoute
  '/_authenticated/tc/list': typeof AuthenticatedTcListRoute
  '/_authenticated/tc/mech': typeof AuthenticatedTcMechRoute
  '/_authenticated/tc/progress': typeof AuthenticatedTcProgressRoute
  '/api/public/manpower-sync': typeof ApiPublicManpowerSyncRoute
  '/api/public/safety-report': typeof ApiPublicSafetyReportRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/_authenticated/manpower/': typeof AuthenticatedManpowerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/delays'
    | '/network'
    | '/raw-data'
    | '/report'
    | '/schedule'
    | '/today'
    | '/today-report'
    | '/upload'
    | '/users'
    | '/manpower/compare'
    | '/manpower/masters'
    | '/manpower/members'
    | '/manpower/trend'
    | '/tc/elec'
    | '/tc/list'
    | '/tc/mech'
    | '/tc/progress'
    | '/api/public/manpower-sync'
    | '/api/public/safety-report'
    | '/api/public/version'
    | '/manpower/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/delays'
    | '/network'
    | '/raw-data'
    | '/report'
    | '/schedule'
    | '/today'
    | '/today-report'
    | '/upload'
    | '/users'
    | '/manpower/compare'
    | '/manpower/masters'
    | '/manpower/members'
    | '/manpower/trend'
    | '/tc/elec'
    | '/tc/list'
    | '/tc/mech'
    | '/tc/progress'
    | '/api/public/manpower-sync'
    | '/api/public/safety-report'
    | '/api/public/version'
    | '/manpower'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/delays'
    | '/_authenticated/network'
    | '/_authenticated/raw-data'
    | '/_authenticated/report'
    | '/_authenticated/schedule'
    | '/_authenticated/today'
    | '/_authenticated/today-report'
    | '/_authenticated/upload'
    | '/_authenticated/users'
    | '/_authenticated/manpower/compare'
    | '/_authenticated/manpower/masters'
    | '/_authenticated/manpower/members'
    | '/_authenticated/manpower/trend'
    | '/_authenticated/tc/elec'
    | '/_authenticated/tc/list'
    | '/_authenticated/tc/mech'
    | '/_authenticated/tc/progress'
    | '/api/public/manpower-sync'
    | '/api/public/safety-report'
    | '/api/public/version'
    | '/_authenticated/manpower/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicManpowerSyncRoute: typeof ApiPublicManpowerSyncRoute
  ApiPublicSafetyReportRoute: typeof ApiPublicSafetyReportRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delays': {
      id: '/_authenticated/delays'
      path: '/delays'
      fullPath: '/delays'
      preLoaderRoute: typeof AuthenticatedDelaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raw-data': {
      id: '/_authenticated/raw-data'
      path: '/raw-data'
      fullPath: '/raw-data'
      preLoaderRoute: typeof AuthenticatedRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today-report': {
      id: '/_authenticated/today-report'
      path: '/today-report'
      fullPath: '/today-report'
      preLoaderRoute: typeof AuthenticatedTodayReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manpower/': {
      id: '/_authenticated/manpower/'
      path: '/manpower'
      fullPath: '/manpower/'
      preLoaderRoute: typeof AuthenticatedManpowerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manpower/compare': {
      id: '/_authenticated/manpower/compare'
      path: '/manpower/compare'
      fullPath: '/manpower/compare'
      preLoaderRoute: typeof AuthenticatedManpowerCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manpower/masters': {
      id: '/_authenticated/manpower/masters'
      path: '/manpower/masters'
      fullPath: '/manpower/masters'
      preLoaderRoute: typeof AuthenticatedManpowerMastersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manpower/members': {
      id: '/_authenticated/manpower/members'
      path: '/manpower/members'
      fullPath: '/manpower/members'
      preLoaderRoute: typeof AuthenticatedManpowerMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manpower/trend': {
      id: '/_authenticated/manpower/trend'
      path: '/manpower/trend'
      fullPath: '/manpower/trend'
      preLoaderRoute: typeof AuthenticatedManpowerTrendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tc/elec': {
      id: '/_authenticated/tc/elec'
      path: '/tc/elec'
      fullPath: '/tc/elec'
      preLoaderRoute: typeof AuthenticatedTcElecRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tc/list': {
      id: '/_authenticated/tc/list'
      path: '/tc/list'
      fullPath: '/tc/list'
      preLoaderRoute: typeof AuthenticatedTcListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tc/mech': {
      id: '/_authenticated/tc/mech'
      path: '/tc/mech'
      fullPath: '/tc/mech'
      preLoaderRoute: typeof AuthenticatedTcMechRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tc/progress': {
      id: '/_authenticated/tc/progress'
      path: '/tc/progress'
      fullPath: '/tc/progress'
      preLoaderRoute: typeof AuthenticatedTcProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/manpower-sync': {
      id: '/api/public/manpower-sync'
      path: '/api/public/manpower-sync'
      fullPath: '/api/public/manpower-sync'
      preLoaderRoute: typeof ApiPublicManpowerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/safety-report': {
      id: '/api/public/safety-report'
      path: '/api/public/safety-report'
      fullPath: '/api/public/safety-report'
      preLoaderRoute: typeof ApiPublicSafetyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDelaysRoute: typeof AuthenticatedDelaysRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedRawDataRoute: typeof AuthenticatedRawDataRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTodayReportRoute: typeof AuthenticatedTodayReportRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedManpowerCompareRoute: typeof AuthenticatedManpowerCompareRoute
  AuthenticatedManpowerMastersRoute: typeof AuthenticatedManpowerMastersRoute
  AuthenticatedManpowerMembersRoute: typeof AuthenticatedManpowerMembersRoute
  AuthenticatedManpowerTrendRoute: typeof AuthenticatedManpowerTrendRoute
  AuthenticatedTcElecRoute: typeof AuthenticatedTcElecRoute
  AuthenticatedTcListRoute: typeof AuthenticatedTcListRoute
  AuthenticatedTcMechRoute: typeof AuthenticatedTcMechRoute
  AuthenticatedTcProgressRoute: typeof AuthenticatedTcProgressRoute
  AuthenticatedManpowerIndexRoute: typeof AuthenticatedManpowerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDelaysRoute: AuthenticatedDelaysRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedRawDataRoute: AuthenticatedRawDataRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTodayReportRoute: AuthenticatedTodayReportRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedManpowerCompareRoute: AuthenticatedManpowerCompareRoute,
  AuthenticatedManpowerMastersRoute: AuthenticatedManpowerMastersRoute,
  AuthenticatedManpowerMembersRoute: AuthenticatedManpowerMembersRoute,
  AuthenticatedManpowerTrendRoute: AuthenticatedManpowerTrendRoute,
  AuthenticatedTcElecRoute: AuthenticatedTcElecRoute,
  AuthenticatedTcListRoute: AuthenticatedTcListRoute,
  AuthenticatedTcMechRoute: AuthenticatedTcMechRoute,
  AuthenticatedTcProgressRoute: AuthenticatedTcProgressRoute,
  AuthenticatedManpowerIndexRoute: AuthenticatedManpowerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicManpowerSyncRoute: ApiPublicManpowerSyncRoute,
  ApiPublicSafetyReportRoute: ApiPublicSafetyReportRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
