/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDelaysRouteImport } from './routes/_authenticated/delays'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedRawDataRouteImport } from './routes/_authenticated/raw-data'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTcElecRouteImport } from './routes/_authenticated/tc.elec'
import { Route as AuthenticatedTcListRouteImport } from './routes/_authenticated/tc.list'
import { Route as AuthenticatedTcMechRouteImport } from './routes/_authenticated/tc.mech'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDelaysRoute = AuthenticatedDelaysRouteImport.update({
  id: '/delays',
  path: '/delays',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRawDataRoute = AuthenticatedRawDataRouteImport.update({
  id: '/raw-data',
  path: '/raw-data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTcElecRoute = AuthenticatedTcElecRouteImport.update({
  id: '/tc/elec',
  path: '/tc/elec',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTcListRoute = AuthenticatedTcListRouteImport.update({
  id: '/tc/list',
  path: '/tc/list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTcMechRoute = AuthenticatedTcMechRouteImport.update({
  id: '/tc/mech',
  path: '/tc/mech',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delays': typeof AuthenticatedDelaysRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/raw-data': typeof AuthenticatedRawDataRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/users': typeof AuthenticatedUsersRoute
  '/tc/elec': typeof AuthenticatedTcElecRoute
  '/tc/list': typeof AuthenticatedTcListRoute
  '/tc/mech': typeof AuthenticatedTcMechRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delays': typeof AuthenticatedDelaysRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/raw-data': typeof AuthenticatedRawDataRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/users': typeof AuthenticatedUsersRoute
  '/tc/elec': typeof AuthenticatedTcElecRoute
  '/tc/list': typeof AuthenticatedTcListRoute
  '/tc/mech': typeof AuthenticatedTcMechRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/delays': typeof AuthenticatedDelaysRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/raw-data': typeof AuthenticatedRawDataRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/tc/elec': typeof AuthenticatedTcElecRoute
  '/_authenticated/tc/list': typeof AuthenticatedTcListRoute
  '/_authenticated/tc/mech': typeof AuthenticatedTcMechRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/delays'
    | '/network'
    | '/raw-data'
    | '/schedule'
    | '/upload'
    | '/users'
    | '/tc/elec'
    | '/tc/list'
    | '/tc/mech'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/delays'
    | '/network'
    | '/raw-data'
    | '/schedule'
    | '/upload'
    | '/users'
    | '/tc/elec'
    | '/tc/list'
    | '/tc/mech'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/delays'
    | '/_authenticated/network'
    | '/_authenticated/raw-data'
    | '/_authenticated/schedule'
    | '/_authenticated/upload'
    | '/_authenticated/users'
    | '/_authenticated/tc/elec'
    | '/_authenticated/tc/list'
    | '/_authenticated/tc/mech'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delays': {
      id: '/_authenticated/delays'
      path: '/delays'
      fullPath: '/delays'
      preLoaderRoute: typeof AuthenticatedDelaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raw-data': {
      id: '/_authenticated/raw-data'
      path: '/raw-data'
      fullPath: '/raw-data'
      preLoaderRoute: typeof AuthenticatedRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tc/elec': {
      id: '/_authenticated/tc/elec'
      path: '/tc/elec'
      fullPath: '/tc/elec'
      preLoaderRoute: typeof AuthenticatedTcElecRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tc/list': {
      id: '/_authenticated/tc/list'
      path: '/tc/list'
      fullPath: '/tc/list'
      preLoaderRoute: typeof AuthenticatedTcListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tc/mech': {
      id: '/_authenticated/tc/mech'
      path: '/tc/mech'
      fullPath: '/tc/mech'
      preLoaderRoute: typeof AuthenticatedTcMechRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDelaysRoute: typeof AuthenticatedDelaysRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedRawDataRoute: typeof AuthenticatedRawDataRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedTcElecRoute: typeof AuthenticatedTcElecRoute
  AuthenticatedTcListRoute: typeof AuthenticatedTcListRoute
  AuthenticatedTcMechRoute: typeof AuthenticatedTcMechRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDelaysRoute: AuthenticatedDelaysRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedRawDataRoute: AuthenticatedRawDataRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedTcElecRoute: AuthenticatedTcElecRoute,
  AuthenticatedTcListRoute: AuthenticatedTcListRoute,
  AuthenticatedTcMechRoute: AuthenticatedTcMechRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
